# Shadowrocket 完整配置；策略组通过订阅节点正则自动装载
[General]
dns-server = https://doh.pub/dns-query,https://dns.alidns.com/dns-query
fallback-dns-server = 223.5.5.5,119.29.29.29
ipv6 = true

[Proxy Group]
日常代理 = url-test,policy-regex-filter=^(?!.*(?:流量|到期|剩余|官网|套餐)).+$,url=http://www.gstatic.com/generate_204,interval=300,tolerance=50
敏感服务 = select,policy-regex-filter=^(?!.*(?:流量|到期|剩余|官网|套餐)).+$
直连优先 = select,DIRECT,日常代理
广告拦截 = select,REJECT,DIRECT

[Rule]
DOMAIN-SUFFIX,byteimg.com,DIRECT
DOMAIN-SUFFIX,ibytedtos.com,DIRECT
DOMAIN-SUFFIX,volccdn.com,DIRECT
DOMAIN-SUFFIX,volcdns.com,DIRECT
DOMAIN-SUFFIX,volceapi.com,DIRECT
DOMAIN-SUFFIX,volcengine-api.com,DIRECT
DOMAIN-SUFFIX,volcengine.com,DIRECT
DOMAIN-SUFFIX,volcengine.net,DIRECT
DOMAIN-SUFFIX,volcengineapi.com,DIRECT
DOMAIN-SUFFIX,volces.com,DIRECT
DOMAIN-SUFFIX,volcimagex.com,DIRECT
DOMAIN-SUFFIX,volcvideo.com,DIRECT
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/rules/reject.list,广告拦截
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/shadowrocket/geosite/ads.list,广告拦截
IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
IP-CIDR,169.254.0.0/16,DIRECT,no-resolve
IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
IP-CIDR,240.0.0.0/4,DIRECT,no-resolve
IP-CIDR6,::1/128,DIRECT,no-resolve
IP-CIDR6,fc00::/7,DIRECT,no-resolve
IP-CIDR6,fe80::/10,DIRECT,no-resolve
IP-CIDR6,ff00::/8,DIRECT,no-resolve
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/rules/sensitive.list,敏感服务
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/shadowrocket/geosite/sensitive.list,敏感服务
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/rules/direct.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/shadowrocket/geosite/cn.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/rules/direct-preferred.list,直连优先
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/rules/proxy.list,日常代理
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/shadowrocket/geosite/proxy.list,日常代理
RULE-SET,https://raw.githubusercontent.com/Luca4Don3/clash-rules/master/shadowrocket/geosite/ipcn.list,DIRECT
GEOIP,CN,DIRECT
FINAL,DIRECT
